### ISSUE TITLE
Data-api-client scope related to serverless issues and your other tool mysql

### ISSUE THREAD

**Issue by misner** [jeremydaly/data-api-client#7]
Hi Jeremy !

Thanks so much for this really great wrapper.

I also read your article: https://www.jeremydaly.com/serverless-mysql-at-scale/, where you mention another tool of yours (https://github.com/jeremydaly/serverless-mysqL) because serverless raises a lot of issues such as max_connections...

I'm using the DATa API today but I wonder: does data-api-client and the DATA-API itself solve the issues you raised in [your article](https://www.jeremydaly.com/serverless-mysql-at-scale/,) or **should I use both your DATA-API -CLIENT with at the same time  SERVERLESS-MYSQL** ?

Maybe the aws DATA-API actually solves the issues you raised in https://www.jeremydaly.com/serverless-mysql-at-scale/ but it's not toally crystal clear for me.

**Comment by jeremydaly** [comment]
Hi @misner,

You **do not** need to use both of them together. The Data API solves the `max_connections` issue because AWS handles the connection pooling for you. There are other issues with the Data API in terms of latency, but for the most part, it works really well. `serverless-mysql` is for connecting *directly* to your MySQL instance. In that case, the `max_connections` issue is handled by the package by monitoring the number of connections and auto disconnecting/killing zombies for you.

Hope that helps,
Jeremy

**Comment by misner** [comment]
Very clear thanks!
